language: c

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libmpich-dev
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
         - build_label="gcc-4.9 mpich" 

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libopenmpi-dev
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
         - build_label="gcc-4.9 openmpi" 

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libmpich-dev
            - libhdf5-mpich-dev
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
         - build_label="gcc-4.9 mpich hdf5"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libopenmpi-dev
            - libhdf5-openmpi-dev
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
         - build_label="gcc-4.9 openmpi hdf5"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libmpich-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - build_label="gcc-7 mpich"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libopenmpi-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - build_label="gcc-7 openmpi"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libmpich-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
        - build_label="clang-5.0 mpich"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libopenmpi-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
        - build_label="clang-5.0 openmpi"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libmpich-dev
            - libhdf5-mpich-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
        - build_label="clang-5.0 mpich hdf5"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libopenmpi-dev
            - libhdf5-openmpi-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
        - build_label="clang-5.0 openmpi hdf5"

before_install:
    - test -n $CC && unset CC
    - eval "${MATRIX_EVAL}"
    - mpicc -v

script:
    - ./bootstrap && ./configure && make && make check


