language: c

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libmpich-dev
      env:
         - MATRIX_EVAL=""
         - extra_configure_options=""
         - build_label="mpich" 

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libopenmpi-dev
      env:
         - MATRIX_EVAL=""
         - extra_configure_options=""
         - build_label="openmpi" 

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libmpich-dev
            - libhdf5-mpich2-dev
      env:
         - MATRIX_EVAL=""
         - extra_configure_options="--with-hdf5"
         - build_label="mpich hdf5"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libopenmpi-dev
            - libhdf5-openmpi-dev
      env:
         - MATRIX_EVAL=""
         - extra_configure_options="--with-hdf5"
         - build_label="openmpi hdf5"


before_install:
    - test -n $CC && unset CC
    - eval "${MATRIX_EVAL}"
    - mpicc -v

script:
    - ./bootstrap && ./configure ${extra_configure_options} && make && make check


